default_host_key: localhost1
storage_dirs:
    ncats1:
      type: 'aws'
      dir:  's3:://gsrs-storage/'
host_keys:
  localhost1:
    base_url: http://localhost:8081/api/v1/
    auth_username: admin
    auth_method: auth-password
    auth_method_value: admin
logging:
  general:
    standard: 1
    timer: 1
    startend: 0
    adhoc: 1
    request: 0
    response: 0
    exceptions: 1
    traceback: 1
  defined:
    request: 1
    response: 1





 






