default_host_key: localhost1
auth_username: admin
auth_password: admin
auth_key: none
host_keys:
  localhost1:
    base_url: http://localhost:8081/api/v1/
    auth_username: admin
    auth_password: admin
    auth_key: none
verbose:
  log_start_stop: 1
  json_request: 1
  json_response: 1
  exceptions: 1
